# Path is still needed for backward compatibility, but will be used only to locate config
SourcePath=C&#58;\\MyDocuments\\03Business\\05ResearchAndAnalysis\\StockInvestments\\QuarterResultsScreenerExcels

# Update only files modified in the last 2 days (i.e. today + yesterday)
FilesToBeUpdated=120Min

