# Config File to split KOTAK and AMBIT Daily Report PDF into indiviual Stock Reports.

#cd C:\MyDocuments\03Business\05ResearchAndis\StockInvestments\ResearchReports\CompanyResearchReports\KotakDaily
#javac -cp .;pdfbox_2.jar;log1.2.mar PdfSplitter.java
#jar cvmf MANIFEST.MF pdfsplitter.jar PdfSplitter.class pdfbox_2.jar;log1.2.jar
#java -cp pdfsplitter.jar;pdfbox_2.jar;log1.2.jar PdfSplitter



