# Config File to Extract Report Parameters from Report PDFs

########## Common Parameters ##########

ReportDataExtractConfigFilePath=C:\\MyDocuments\\03Business\\05ResearchAndAnalysis\\StockInvestments\\ResearchReports\\CompanyResearchReports\\ReportDataExtractConfig2.0.xlsx
#ReportDataExtractConfigFilePath=C:\\MyDocuments\\03Business\\05ResearchAndAnalysis\\StockInvestments\\ResearchReports\\CompanyResearchReports\\ReportDataExtractConfig.xlsx
AnalystNamesFilePath=C:\\MyDocuments\\03Business\\05ResearchAndAnalysis\\StockInvestments\\ResearchReports\\CompanyResearchReports\\AnalystNames.xlsx

########## Common Parameters ##########

