[FocusFive]
tickers=VENUSPIPES,ANUP,EMMVEE,ACMESOLAR,HDFCAMC

[HeatExchanger]
tickers=LT,THERMAX,TEGA,ANUP,KRN

[SteelPipes]
tickers=APLAPOLLO,HARIOMPIPE,HITECH,JINDALSAW,JTLIND,KIRLFER,MAHSEAMLES,RAMASTEEL,RATNAMANI,SAMBHV,SURYAROSNI,VENUSPIPES,WELCORP

[Solar]
tickers=WAAREEENER,APARINDS,PREMIERENE,VIKRAMSOLR,EMMVEE,SAATVIKGL

[Banks]
tickers=HDFCBANK,SBIN,ICICIBANK,AXISBANK,KOTAKBANK,AUBANK,INDUSINDBK,FEDERALBNK,IDFCFIRSTB

[LatestIPOs]
tickers=ICICIAMC,MEESHO,GROWW,LENSKART,LGEINDIA